name: Test setlocale
on: [push]
jobs:
  test:
    name: Test setlocale
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with: { perl-version: latest }
      - run: perl -MPOSIX -E "say POSIX::setlocale(POSIX::LC_ALL)"
        env: { LC_ALL: English_United States.1252 }